# Generated by Django 5.2 on 2025-04-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='session_thumbnails/', verbose_name='thumbnail'),
        ),
        migrations.AddField(
            model_name='session',
            name='topics_to_cover',
            field=models.TextField(blank=True, help_text='List of topics that will be covered in this session', verbose_name='topics to cover'),
        ),
    ]
